service: bp-server

plugins:
 - serverless-offline

provider:
 name: aws
 runtime: nodejs18.x

functions:
 main:
   handler: dist/main.handler
   events:
     - http:
         method: any
         path: /{any+}
         cors: true

